#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-fill $HOME/wallpaper/bg_1.jpg
picom &

primary_monitor=$(xrandr -q | grep " primary" | awk '{print $1}')
if [[ ! -f /tmp/bspwm_initialized ]]; then
    $HOME/load-monitor.sh
    touch /tmp/bspwm_initialized
    bspc config -m $(bspc query -M | head -n 1) top_padding 0
fi

must_create=1
for f in `bspc query -M`; do
    bspc monitor $f -d $must_create
    must_create=$((must_create + 1))
done

eww open bar

bspc config border_width         0
bspc config window_gap         	32

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle     false

bspc config honor_fullscreen true
bspc config remove_unneeded_padding true

bpsc config top_padding 0

for m in $(bspc query -M); do
    bspc config -m "$m" top_padding 0
done

bspc config -m $primary_monitor top_padding 48

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
