# reload config
bind=SUPER,r,reload_config

# open terminal
bind=SUPER,Return,spawn,kitty

# open browser
bind=SUPER+SHIFT,f,spawn,env GDK_BACKEND=wayland MOZ_ENABLE_WAYLAND=1 firefox

# window interactions
bind=SUPER,w,killclient

bind=SUPER,Tab,focusstack,next
bind=SUPER,Left,focusdir,left
bind=SUPER,Right,focusdir,right
bind=SUPER,Up,focusdir,up
bind=SUPER,Down,focusdir,down

bind=ALT+SHIFT,Up,exchange_client,up
bind=ALT+SHIFT,Down,exchange_client,down
bind=ALT+SHIFT,Left,exchange_client,left
bind=ALT+SHIFT,Right,exchange_client,right

bind=SUPER,f,togglefullscreen,

bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

bind=SUPER,space,spawn_shell,pkill -f "^quickshell -c .*runner" || quickshell -c ~/dotfiles/.config/quickshell/runner/
bind=NONE,Print,spawn_shell,wayfreeze --after-freeze-cmd 'grim -g "$(slurp)" - | wl-copy; killall wayfreeze'

bind=SUPER+SHIFT,Left,tagmon,left
bind=SUPER+SHIFT,Right,tagmon,right
bind=SUPER+SHIFT,l,spawn,sh -c "~/dotfiles/.config/mango/wallpaper.sh toggle"
