include-file = $HOME/.config/polybar/colors.ini

# bars
include-file = $HOME/.config/polybar/coolbar_1.ini
include-file = $HOME/.config/polybar/coolbar_2.ini
include-file = $HOME/.config/polybar/coolbar_3.ini

include-file = $HOME/.config/polybar/modules/date.ini
include-file = $HOME/.config/polybar/modules/tray.ini
include-file = $HOME/.config/polybar/modules/bspwm.ini
include-file = $HOME/.config/polybar/modules/pulseaudio.ini
include-file = $HOME/.config/polybar/modules/cpu.ini
include-file = $HOME/.config/polybar/modules/memory.ini

[settings]
pseudo-transparency = true
screenchange-reload = true
